# .streamlit/secrets.toml
# OPENAI_API_KEY = "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"
GOOGLE_API_KEY="AIzaSyDBFQlFQS8KO-QVIY7cdPpZDgnMCmQlU7U"      # GOOGLE API KEY baru pada https://aistudio.google.com/apikey
# GROQ_API_KEY="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"    # Buat GROQ API KEY baru pada https://console.groq.com/keys
LANGCHAIN_API_KEY = "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"
OCR_SPACE_API_KEY="
